# Generated by Django 4.0.4 on 2022-06-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0003_userprofile_location_alter_userprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_app.neighborhood'),
        ),
    ]
