# Generated by Django 4.0.4 on 2022-06-19 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch_app', '0004_userprofile_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to=settings.AUTH_USER_MODEL),
        ),
    ]
