# Generated by Django 4.0.4 on 2022-06-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0006_rename_block_userprofile_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='facility_images')),
                ('location', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighborhood', models.ManyToManyField(blank=True, related_name='facilities', to='watch_app.neighborhood')),
            ],
        ),
    ]
