# Generated by Django 4.0.4 on 2022-06-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0007_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='neighborhood', to='watch_app.facility'),
        ),
    ]
