# Generated by Django 4.0.4 on 2022-06-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0009_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='business',
            field=models.ManyToManyField(blank=True, related_name='business', to='watch_app.business'),
        ),
    ]
