# Generated by Django 4.0.4 on 2022-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0011_alter_neighborhood_business_post_neighborhood_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='neighborhood', to='watch_app.post'),
        ),
    ]
